# Generated by Django 3.2.8 on 2022-05-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbeck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ф.И.О')),
                ('phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('poter', models.BooleanField(default=False, verbose_name='Портер')),
                ('movers', models.BooleanField(default=False, verbose_name='Грузчики')),
                ('dispersal', models.BooleanField(default=False, verbose_name='Разборка/сборка мебели')),
                ('trash', models.BooleanField(default=False, verbose_name='Вызов мусора')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
        ),
    ]
