# Generated by Django 3.2.8 on 2022-05-08 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbeck', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbeck',
            options={'verbose_name': 'Форма братной сяви', 'verbose_name_plural': 'Форма братной сяви'},
        ),
    ]
