# Generated by Django 3.2.8 on 2022-05-08 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbeck', '0002_alter_feedbeck_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbeck',
            new_name='Feedback',
        ),
    ]
